export const ADD_FACILITIES = "ADD_FACILITIES";
export const REMOVE_FACILITIES = "REMOVE_FACILITIES";
export const UPDATE_AFFORDABLE = "UPDATE_AFFORDABLE";

export const RESET_FACILITIES = "RESET_FACILITIES";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const ORDER_LOAD_FAILED = "ORDER_LOAD_FAILED";


export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";